spring.application.name=LonieBot
# 填入你在 LINE Developers 看到的 Channel Access Token
line.bot.channel-token=GpabkHNbH/vBqV57z/cB1G/WB/cEy/jQtkxsMT9a0iNjmUMs3nhioD021LNNtLhq+nrP+NW2kRqFcHwbN18fchSjz+NsdH+8k9Pa06IXQqtS6oYFbC2Lsr6oT0pbiEaWQYxTz3jHVJSUJXsnx5yuzAdB04t89/1O/w1cDnyilFU=
# 填入你在 LINE Developers 看到的 Channel Secret
line.bot.channel-secret=990a8b5850f492d166030cd4da95f34e
# 這是我們跟 LINE 約定好的路徑
line.bot.handler.path=/callback
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
# Gemini 設定
gemini.api-key=AIzaSyDu0FoaMn0KPvdBFsOCtITLYXNbsWENl8s
# 停用 DevTools 自動重啟 (如果你覺得太煩的話)
spring.devtools.restart.enabled=false
# 或者設定排除特定資料夾
spring.devtools.restart.exclude=static/**,public/**